// <auto-generated />
using Acourse.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Acourse.Migrations
{
    [DbContext(typeof(courseContext))]
    partial class courseContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Acourse.Models.course", b =>
                {
                    b.Property<int>("courseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("cname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("describtion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("fieldId")
                        .HasColumnType("int");

                    b.HasKey("courseId");

                    b.HasIndex("fieldId");

                    b.ToTable("courses");

                    b.HasData(
                        new
                        {
                            courseId = 1,
                            cname = "c++",
                            describtion = "this is a good course",
                            fieldId = 1
                        },
                        new
                        {
                            courseId = 2,
                            cname = "java",
                            describtion = "this is a good course java",
                            fieldId = 1
                        },
                        new
                        {
                            courseId = 3,
                            cname = "physics",
                            describtion = "this is a good course",
                            fieldId = 2
                        },
                        new
                        {
                            courseId = 4,
                            cname = "dental lab",
                            describtion = "this is a good course",
                            fieldId = 3
                        });
                });

            modelBuilder.Entity("Acourse.Models.field", b =>
                {
                    b.Property<int>("fieldId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fname")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("fieldId");

                    b.ToTable("fields");

                    b.HasData(
                        new
                        {
                            fieldId = 2,
                            description = "scienes fields",
                            fname = "scienes"
                        },
                        new
                        {
                            fieldId = 1,
                            description = "it fields",
                            fname = "it"
                        },
                        new
                        {
                            fieldId = 3,
                            description = "medicin fields",
                            fname = "medicin"
                        });
                });

            modelBuilder.Entity("Acourse.Models.user", b =>
                {
                    b.Property<int>("userId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("uname")
                        .HasColumnType("nvarchar(max)");
                    b.Property<string>("password")
                     .HasColumnType("nvarchar(max)");
                    b.Property<string>("email")
                     .HasColumnType("nvarchar(max)");

                    b.HasKey("userId");

                    b.ToTable("uesrs");
                    b.HasData(
                        new
                        {
                            userId = 1,
                            uname = "showq",
                            email = "showq@hotmail"
                        },
                        new
                        {
                            userId = 2,
                            uname = "suha",
                            email = "suha@hotmail"
                        });
                });

            modelBuilder.Entity("Acourse.Models.course", b =>
                {
                    b.HasOne("Acourse.Models.field", "field")
                        .WithMany()
                        .HasForeignKey("fieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
